name: Build

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.repository == 'mobile-dev-inc/maestro'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8

      - uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew :maestro-cli:installDist -q
        
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
          retention-days: 5
